const express = require("express");
const customerController = require("../controller/CustomerController");
const router = express.Router();
const verifyUser = require("../middleware/AuthMiddlewear");
//router.post("/create",verifyUser,customerController.create);
router.post("/create",verifyUser,customerController.create);
router.get("/find-by-id/:id",verifyUser,customerController.findById);
router.delete("/delete-by-id/:id",verifyUser,customerController.deleteById);
router.put("/update/:id",verifyUser,customerController.update);
router.get("/find-all",verifyUser,customerController.findAll);
router.get("/find-counts",verifyUser,customerController.findCustomerCounts);
module.exports = router;
